"""Fix progress column

Revision ID: 01be9a1ba9eb
Revises: b8bc9b52dec0
Create Date: 2025-01-30 06:28:34.031978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01be9a1ba9eb'
down_revision = 'b8bc9b52dec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.alter_column('progress',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.alter_column('progress',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
