"""more columns

Revision ID: 146db3c4fa1a
Revises: 249b9a070f37
Create Date: 2025-01-31 08:39:54.280047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146db3c4fa1a'
down_revision = '249b9a070f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
