"""got rid of grade

Revision ID: 249b9a070f37
Revises: c5f371dbd69a
Create Date: 2025-01-31 06:39:30.361157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249b9a070f37'
down_revision = 'c5f371dbd69a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_column('grade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
