"""Final fixes

Revision ID: c5f371dbd69a
Revises: 01be9a1ba9eb
Create Date: 2025-01-30 10:49:23.227288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f371dbd69a'
down_revision = '01be9a1ba9eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
